---
# Source: superset/templates/secret-env.yaml
apiVersion: v1
kind: Secret
metadata:
  name: superset-env
  namespace: default
  labels:
    app: superset
    chart: superset-0.12.5
    release: "superset"
    heritage: "Helm"
type: Opaque
stringData:
    REDIS_HOST: "superset-redis-headless"
    REDIS_USER: ""
    REDIS_PORT: "6379"
    REDIS_PROTO: "redis"
    REDIS_DB: "1"
    REDIS_CELERY_DB: "0"
    DB_HOST: "superset-postgresql"
    DB_PORT: "5432"
    DB_USER: "superset"
    DB_PASS: "superset"
    DB_NAME: "superset"
    DB_DIALECT: "postgresql"
    DATABASE_DB: "superset"
    DATABASE_HOST: "superset-postgresql"
    DATABASE_PASSWORD: "superset"
    DATABASE_USER: "superset"
    DATABASE_PORT: "5432"
    DATABASE_DIALECT: "postgresql"
    SUPERSET_LOAD_EXAMPLES: "no"
    SUPERSET_SECRET_KEY: "TEST_NON_DEV_SECRET"
    CYPRESS_CONFIG: "false"
    SUPERSET_PORT: "8088"
    MAPBOX_API_KEY: ''
    SUPERSET_SECRET_KEY: "CHANGE_ME"
    SUPERSET_FEATURE_ROW_LEVEL_SECURITY: "true"
    SUPERSET_FEATURE_DASHBOARD_RBAC: "true"
    SUPERSET_FEATURE_ALERT_REPORTS: "true"
    SUPERSET_FEATURE_EMBEDDED_SUPERSET: "true"
    SUPERSET_FEATURE_ENABLE_TEMPLATE_PROCESSING: "true"
    SUPERSET_SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://superset:superset@superset-postgresql:5432/superset"
    TALISMAN_ENABLED: "true"
    SUPERSET_GUEST_TOKEN_JWT_SECRET: "CHANGE_ME"
    SUPERSET_GUEST_TOKEN_JWT_AUDIENCE: "http://superset:8088/"
