---
# Source: superset/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: superset
  namespace: default
  labels:
    app: superset
    chart: superset-0.12.5
    release: superset
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: superset
    release: superset
